language: ruby

git:
  submodules: false

before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - export AWS_DEFAULT_REGION=eu-west-1
  - echo "Installing test gems"
  - gem install yaml-lint

# skip install step 
install: true

script:
  - aws cloudformation validate-template --template-body file://deploy.yml
  - yaml-lint deploy.yml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation template validated"
  - echo "Automate Deployment YAML linted"

#notifications:
#  slack: chefio:NjT9ciXFpaYefpwaFxS1n4LN